# Generated by Django 4.2.7 on 2025-09-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_uploadedfile_file_category_userprofile_fileaccesslog"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="file_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
