# Generated by Django 4.2.7 on 2025-09-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_uploadedfile_file_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[("user", "User"), ("admin", "Admin")],
                default="user",
                max_length=10,
            ),
        ),
    ]
