# Generated by Django 4.2.7 on 2025-10-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_userprofile_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="file",
            field=models.CharField(max_length=500),
        ),
    ]
